stages:
  librespeech:
    foreach: ${datasets.librespeech}
    do:
      cmd: |
        wget https://www.openslr.org/resources/12/${item}.tar.gz -P data
        tar -xvf data/${item}.tar.gz -C data
        rm data/${item}.tar.gz
      outs:
        - data/LibriSpeech/${item}
